# Generated by Django 5.0.4 on 2026-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
