# Generated by Django 5.0.4 on 2026-04-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_activity_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
