# Generated by Django 5.0.4 on 2026-06-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='activity_attachments/'),
        ),
    ]
