# Generated by Django 5.0.4 on 2026-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_activity_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('referral', 'Referral'), ('website', 'Website'), ('linkedin', 'LinkedIn'), ('cold_call', 'Cold Call'), ('social_media', 'Social Media'), ('event', 'Event / Exhibition'), ('partner', 'Partner'), ('other', 'Other')], max_length=20),
        ),
    ]
