# Generated by Django 5.0.4 on 2026-07-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deal_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
