# Generated by Django 5.0.4 on 2026-07-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_deal_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
