# Generated by Django 5.0.4 on 2026-07-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notification_tag'),
        ('leads', '0008_lead_lost_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='dashboard.tag'),
        ),
    ]
