# Generated by Django 5.0.4 on 2026-07-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clients', '0004_client_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recurrence', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='Day of month to generate invoice (1–28)')),
                ('payment_due_days', models.PositiveSmallIntegerField(default=30, help_text='Days until invoice is due')),
                ('next_date', models.DateField(help_text='Next generation date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='clients.client')),
            ],
            options={
                'ordering': ['next_date'],
            },
        ),
    ]
