# Generated by Django 5.0.4 on 2026-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_industry_client_notes_client_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinteraction',
            name='follow_up_done',
            field=models.BooleanField(default=False),
        ),
    ]
