# Generated by Django 5.0.4 on 2026-07-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientinteraction_follow_up_done'),
        ('dashboard', '0002_notification_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='dashboard.tag'),
        ),
    ]
