# Generated by Django 5.0.4 on 2026-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(choices=[('Rs.', 'Rs. (Rupee — text)'), ('₹', '₹ (Indian Rupee symbol)'), ('NPR', 'NPR (Nepalese Rupee)'), ('$', '$ (US Dollar)'), ('£', '£ (British Pound)'), ('€', '€ (Euro)'), ('¥', '¥ (Yen / Yuan)')], default='Rs.', max_length=10)),
                ('number_format', models.CharField(choices=[('indian', 'Indian  —  1,50,000'), ('western', 'Western  —  150,000')], default='indian', max_length=10)),
                ('date_format', models.CharField(choices=[('j M Y', 'D Mon YYYY  — 27 Jun 2025'), ('d/m/Y', 'DD/MM/YYYY  — 27/06/2025'), ('m/d/Y', 'MM/DD/YYYY  — 06/27/2025'), ('Y-m-d', 'YYYY-MM-DD  — 2025-06-27'), ('j F Y', 'D Month YYYY  — 27 June 2025')], default='j M Y', max_length=20)),
                ('fiscal_year_start', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=4, help_text='Month the financial year begins (1 = Jan, 4 = Apr)')),
                ('business_name', models.CharField(default='My Business', max_length=200)),
                ('business_tagline', models.CharField(blank=True, max_length=300)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=50)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_website', models.URLField(blank=True)),
                ('tax_number', models.CharField(blank=True, help_text='GST / VAT / PAN number shown on documents', max_length=100)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('quote_prefix', models.CharField(default='Q', max_length=20)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default tax % applied on new invoices / quotes', max_digits=5)),
                ('default_payment_terms', models.TextField(blank=True, default='Payment due within 30 days of invoice date.')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
