# Generated by Django 5.0.4 on 2026-07-02 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_site_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(choices=[('#6366f1', 'Indigo'), ('#3b82f6', 'Blue'), ('#10b981', 'Green'), ('#f59e0b', 'Amber'), ('#ef4444', 'Red'), ('#8b5cf6', 'Purple'), ('#06b6d4', 'Cyan'), ('#f97316', 'Orange'), ('#64748b', 'Slate'), ('#ec4899', 'Pink')], default='#6366f1', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('lead', 'Lead'), ('followup', 'Follow-up'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('system', 'System')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
