# Generated by Django 5.0.4 on 2026-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='razorpay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
